version: '2'

services:
  app:
    build: .
    restart: always
    working_dir: /project
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/project
      - ./cache:/project/cache
      - ./logs:/project/logs
      - ./conf/php/cli.ini:/etc/php/7.0/cli/conf.d/100-custom.ini
      - ./conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/100-custom.ini
    env_file:
      - ../variables.env

  mysql:
    restart: always
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - ../variables.env