<h1>EDIT</h1>

<form action="/shop/update" method="POST">

	<p>
		<label for="name">Name</label>
		<input type="text" id="name" name="name">
	</p>

	<p>
		<input type="submit" value="Update">
	</p>

</form>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
$(function(){
	var arg = new Object;
	var pair=location.search.substring(1).split('&');
	for(var i=0;pair[i];i++) {
		var kv = pair[i].split('=');
		arg[kv[0]]=kv[1];
	}

	if(!arg.id){
		location.href="/shop";
	}

	$.ajax({
		url:"/shop/get?id="+arg.id,
		type:"get"
	}).done(function(data){
		//何も帰ってこなかったらそのidの商品は存在しないよ
		if(!data){
			location.href="/shop";//topに移動する
		}
		
		var id='<input type="hidden" name="id" value="'+data.id+'">';
		$("form").append(id);
		$("#name").val(data.name);
	});
});
</script>