<h1>CREATE</h1>

<form enctype="multipart/form-data" action="/product/store" method="POST">

	<p>
		<label for="image">Image</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="30000">
		<input type="file" id="image" name="image">
	</p>

	<p>
		<label for="title">Title</label>
		<input type="text" id="title" name="title">
	</p>

	<p>
		<label for="description">Description</label>
		<textarea id="description" name="description"></textarea>
	</p>

	<p>
		<label for="price">Price</label>
		<input type="text" id="price" name="price">
	</p>

	<p>
		<input type="submit" value="Store">
	</p>

</form>