<h1>EDIT</h1>

<form enctype="multipart/form-data" action="/product/update" method="POST">

	<!-- 元々の画像が表示される場所 -->
	<p id="preview_image">

	</p>

	<p>
		<label for="image">Image</label>
		<input type="file" id="image" name="image">
	</p>

	<p>
		<label for="title">Title</label>
		<input type="text" id="title" name="title">
	</p>

	<p>
		<label for="description">Description</label>
		<textarea id="description" name="description"></textarea>
	</p>

	<p>
		<label for="price">Price</label>
		<input type="text" id="price" name="price">
	</p>

	<p>
		<input type="submit" value="Update">
	</p>

</form>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>
$(function(){
	var arg = new Object;
	var pair=location.search.substring(1).split('&');
	for(var i=0;pair[i];i++) {
		var kv = pair[i].split('=');
		arg[kv[0]]=kv[1];
	}

	if(!arg.id){
		location.href="/product";
	}

	$.ajax({
		url:"/product/get?id="+arg.id,
		type:"get"
	}).done(function(data){
		//何も帰ってこなかったらそのidの商品は存在しないよ
		if(!data){
			location.href="/product";//topに移動する
		}

		var img="<img src='/product_images/"+data.image+"'>";
		var id='<input type="hidden" name="id" value="'+data.id+'">';
		$("#preview_image").append(img);
		$("#title").val(data.title);
		$("#description").val(data.description);
		$("#price").val(data.price);
		$("form").append(id);
	});
});
</script>